version: "3"
services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=private_diary
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
    - 3306:3306
    volumes:
    - ./db/init:/docker-entrypoint-initdb.d
    - ./db/conf:/etc/mysql/conf.d
